write-kubeconfig-mode: "0644"
tls-san:
  - "cp1"
  - "cp2"
  - "cp3"
  - "cp1.home"
  - "cp2.home"
  - "cp3.home"
debug: true
cni:
  - "multus"
  - "cilium"
disable-kube-proxy: true
embedded-registry: true
kube-apiserver-arg:
  - "audit-log-path=/var/log/rke2/audit.log"
  - "audit-log-maxage=40"
  - "audit-log-maxbackup=15"
  - "audit-log-maxsize=150"
